### ISSUE TITLE
LED Light strip support

### ISSUE THREAD

**Issue by StumbleNOLA** [NorthernMan54/homebridge-tasmota#11]
**Is your feature request related to a problem? Please describe:**
The only problem is that RGB strips aren't supported

**Describe the solution you'd like:**
For LED strips to be supported

**Describe alternatives you've considered:**
N/A

**Additional context:**
I appreciate that the plugin specifically says it doesn't not, as of yet, support RGB strips, I am hoping you would change that. Just for fun I set up a strip with a couple (well 3) MOSFETS and a power supply, and it actually seems to import into HomeKit half way. The lights do show up, and the on/off toggle works fine. But there isn't a way to adjust the color, saturation, or brightness from inside HomeKit.

**Comment by NorthernMan54** [comment]
Can you share your Tasmota config for this, and in particular the module type from this screen

Configuration -> Configure Module

And Template if used

For RGB I should not need to grab some hardware this time, just the Tasmota config should do it.

PS These are my RGB lights, just haven't got around to installing Tasmota firmware and working out the config details yet.

https://github.com/NorthernMan54/homebridge-mculed/tree/master/lua

**Comment by StumbleNOLA** [comment]
Here you go. I just noticed that I may have Tasmota-Sensors.bin installed instead of the normal one. I am happy to confirm this, if you think that may be the issue. Before you go digging into it.

<img width="585" alt="Screen Shot 2020-09-17 at 4 06 15 PM" src="https://user-images.githubusercontent.com/44331352/93528288-b8437900-f8ff-11ea-8851-1a23d2370af1.png">


<img width="639" alt="Screen Shot 2020-09-17 at 4 03 37 PM" src="https://user-images.githubusercontent.com/44331352/93528026-5aaf2c80-f8ff-11ea-92e8-d997588b88f1.png">
<img width="630" alt="Screen Shot 2020-09-17 at 4 03 55 PM" src="https://user-images.githubusercontent.com/44331352/93528063-64d12b00-f8ff-11ea-931a-4153912dbe2a.png">
<img width="799" alt="Screen Shot 2020-09-17 at 4 04 53 PM" src="https://user-images.githubusercontent.com/44331352/93528161-87634400-f8ff-11ea-8dba-218ccc9f2d08.png">

**Comment by StumbleNOLA** [comment]
Your schematic is way more complicated than mine (meaning I don't know what many of the parts do). I just have a DC-DC buck converter, a nodeMCU, and three N-channel MOSFET's burins in a case. Oh, and a big spaghetti of wire. I tried to get Fritzing working, but I think their Mac implementation is trash. I couldn't search for parts, and scrolling thru manufacturers one at a time was a joke.

**Comment by StumbleNOLA** [comment]
I don't mean to be a bother, but is there any movement on this or should I look to another plugin?

**Comment by NorthernMan54** [comment]
I’m almost complete with this addition, and should not be much longer.  This is taking a bit longer than I thought origninally as I need to write a color space convertor from HomeKit ( hsb ) to Tasmota ( rgb ) and vice versa.  In my test setup I have changing color working and am working thru status updates.

No need for parts from amazon this time.

**Comment by NorthernMan54** [comment]
If you update to the latest you should now be able to control the colors.  I’m not 100% satisfied with the color conversion code, but this should work.

**Comment by StumbleNOLA** [comment]
Thank you for getting it up and running. I am not qualified to talk about color fidelity, but then I am using cheap strips off of Amazon so meh. But it seems to be working great for me.

**Comment by NorthernMan54** [comment]
What I had seen when testing was a little bit of an argument between my code and Tasmota.  Looked like this

HomeKit change color to X, convert homekit (HSB) X to (RGB) Y
Tasmota ok change color to Y
Tasmota send status update color is now Y
Plugin convert Y (RGB) to X (HSB) and update Homekit 
Oh color has changed, tell Tasmota to change color again

Flipping between Homekit (HSB) to Tasmota (RGB) and back isn't 100 reversible with a couple of color selections.  Small issue but bothersome, need to look at further.

**Comment by StumbleNOLA** [comment]
Working as expected. I have no comment on color correctness. Since I am colorblind, but pure colors seem to be fine.

**Comment by TimVerheul** [comment]
![image](https://user-images.githubusercontent.com/29889196/151549383-5b841efb-cc8f-4e10-9984-8d26fbf88a85.png)

**Comment by TimVerheul** [comment]
Also not sure what 
![image](https://user-images.githubusercontent.com/29889196/151549479-a41c412d-90f9-42d4-9fcb-720c6041b291.png)
this does. I only see in homebridge accessoires that it created this: 
![image](https://user-images.githubusercontent.com/29889196/151549575-e282c68a-42fc-4917-abfc-bd6df68e6842.png)
but that one isn't visable in homekit

**Comment by NorthernMan54** [comment]
Please share your devices tasmota config, I will try recreating it in my setup.

**Comment by TimVerheul** [comment]
> Please share your devices tasmota config, I will try recreating it in my setup.

![image](https://user-images.githubusercontent.com/29889196/151550137-cca043aa-3e34-40e8-aca8-bb6fe4758fdb.png)
you mean this one?

**Comment by TimVerheul** [comment]
![image](https://user-images.githubusercontent.com/29889196/151551493-24de06ef-1f40-4114-9e44-8d5b4ae8b431.png)
When I changed the name of my led strip in Tasmota to something else (so i know which led strip im controlling) and I restarted the plugin i got this message about "Configured Name"

Might be useful

**Comment by TimVerheul** [comment]
@NorthernMan54 I think I found something: the tasmotaLightService.ts on line 67 searches for rgb_cmd_t
My config doesn't have rgb_cmd_t, but has hs_cmd_t (HSBColor)

The code is looking for rgb_cmd_t the whole time, so that might be the reason it thinks this is a "normal" lightbulb

**Comment by NorthernMan54** [comment]
The more recent versions of tasmota changed the discovery object, your going to need to downgrade to an older tasmota version.  Some from before July 2021, or wait until I can code up a fix

Tks for finding this.

https://github.com/arendst/Tasmota/commit/c3d757ca951d8f9ca21d5ae326f553ce4057cd98

**Comment by TimVerheul** [comment]
It is safe to downgrade Tasmota? 

Do you think it cost alot of time to implement the support for the current tasmota version?

**Comment by NorthernMan54** [comment]
I added a new issue to track this, #43, pls continue the discussion there
