### ISSUE TITLE
Tasmota ESP8266 (WeMosD1Mini) doesn‘t reach homebridge

### ISSUE THREAD

**Issue by chimcen** [NorthernMan54/homebridge-tasmota#22]
**Describe Your Problem:**
Hi,
followed your projects long time ago - great stuff! Thank you.
Used (still using it) your mcuiot for my homebridge and just want to switch also to tasmota.
I followed your instructions (flashed Tasmota, set Auto Discovery to on, installed homebridge tasmota, configured it there and also on my tasmota device), but on my tasmota device i‘ll get error „Connection failed .... rc -2“

Is this a problem to use homebridge-mcuiot and homebridge-tasmota at the same time?

How is the tasmota device to configure for use with a BME280?

Can you make such a awesome install/configuration description like the one from your mcuiot project?

**Comment by NorthernMan54** [comment]
I remember you from a few years ago.

As I have been converting all my devices I have been keeping notes here as I needed to convert a lot of devices ( almost 60 ).  My notes per device are here, and I included links to the build instructions for each as they are still running at my homes.

https://github.com/NorthernMan54/homebridge-tasmota/blob/beta/DEVICES.md

Once you have configured all your devices to use Tasmota you need to remove mcuiot.  Tasmota and mcuiot are not compatible with each other and mcuiot will just give errors etc.

**Comment by chimcen** [comment]
Remember me could be good or bad... hahaha :) 

Actually mcuiot doesn‘t make problem - but when i‘m configure my tasmo device correct it will do it for sure.
But running both plugins wouldn‘t interrupt the  connection between the tasmota device and my homebrige?

Checked your templates - 60 devices? Wow...

I used your BME Template and thought i should see then the measurements of BME280 in Tasmota Web GUI - but there is no output...

**Comment by NorthernMan54** [comment]
With the BME sensor you need to use the sensors firmware, as the standard firmware doesn’t do i2c

And when it is working you should see the temperate in the Tasmota device web site 

Over the years I had ended up with a lot of cheap eap8266 devices and had spent the summer flashing them all with tasmota and remove all the random plugins from my setup

In the end I counted them up, and had almost 60 split across my primary residence and vacation property.   I had never realized I had collected that many until I saw them on the tasui list.

**Comment by chimcen** [comment]
What do you mean with "sensors firmware"?

**Comment by NorthernMan54** [comment]
As there are a lot of users of Tasmota, do they have a solution already ?

**Comment by NorthernMan54** [comment]
Glad to hear you got it working, and am glad you have come along on my Tasmota journey

**Comment by chimcen** [comment]
Not completley - in TasUI i found the device and add it. The tasmota console of the device looks also promising, but it didn't apear in my homebridge...

**Comment by chimcen** [comment]
![image](https://user-images.githubusercontent.com/22658487/100489669-fafeaa00-3115-11eb-8c0a-95aad3500f5d.png)
![image](https://user-images.githubusercontent.com/22658487/100489697-1ec1f000-3116-11eb-83c9-37f1c04a4825.png)
![image](https://user-images.githubusercontent.com/22658487/100489710-487b1700-3116-11eb-8208-4b08ff21256c.png)

**Comment by NorthernMan54** [comment]
In my setup I created an alias for my Mosquito server called mqtt.local. And this is saying that it cannot find your mqtt server.

To create the alias, I created this file on my mosquito server

```
nm@jesse:/etc/avahi/services$ cat mosquitto.service 
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
 <name replace-wildcards="yes">Mosquitto MQTT server on %h</name>
  <service>
   <type>_mqtt._tcp</type>
   <port>1883</port>
   <txt-record>info=Publish, Publish! Read all about it! mqtt.org</txt-record>
  </service>
</service-group>
```

**Comment by chimcen** [comment]
I'm stupid... i doesn't have a mosquito server installed cause i thought it would be a subpackage of homebridge-tasmota...

**Comment by chimcen** [comment]
Now it's working... the alias part i've to check later then...

You are using it on debian jesse? Just for info - i'm using it on a Pi4b at debian buster...

**Comment by NorthernMan54** [comment]
I'm on buster as well

I'm using the alias as I have 2 'homes' and keep moving devices back and forth.  Simplifies managing the configurations.  If your not in that scenario, then it may not add a lot of value.

**Comment by chimcen** [comment]
Thought this because of `nm@jesse:` ...nevermind ;)

You're right - but it's more modern and afterwards easier to handle...

Do you have an idea to handle the preasure at sealevel? You remember the task on your mcuiot project?

Btw. thank you for your help. Great as usual

**Comment by NorthernMan54** [comment]
For sea level, start on the Tasmota side.  They have a very large user base and may have already solved the issue, or have a clever work around.  The Tasmota firmware is very feature rich and may surprise you.  I had stopped my own development work on ESP8266's after seeing how feature rich it was, and how far they have progressed in the last few years.

**Comment by chimcen** [comment]
Altidute xxx does the trick. Awesome whats possible with tasmota.

Today i got the response from homebridge (all added tasmota sensors are removed from homebridge automaticly):
"availabilitySubscribe missing ..."

Any idea what this could be?

**Comment by chimcen** [comment]
Found the problem...i set the cleanup interval to 3600 (didn’t want that my homebridge deletes devices that are longer than 24hours are offline...).
Could this be disabled?

**Comment by chimcen** [comment]
I've created the file "/etc/avahi/services/mosquitto.service" and pasted your code - mqtt.local doesn't work anyway... any idea?

**Comment by NorthernMan54** [comment]
Does your setup run 'avahi' ?
