### ISSUE TITLE
Devices found in TasUI but won't appear in homebridge

### ISSUE THREAD

**Issue by Akira-Maia** [NorthernMan54/homebridge-tasmota#30]
Awesome plugin and the auto-discovery feature is amazing. I can find and control my devices in TasUI and add them to saved devices but no matter what I try I can't seem to reveal them as accessories in homebridge. I feel like I'm missing some instruction but it isn't clear from the GitHub page. Maybe install and setup instructions could be a bit more specific.

**Comment by NorthernMan54** [comment]
Did you do this ?

https://github.com/NorthernMan54/homebridge-tasmota#tasmota-device-config
