### ISSUE TITLE
Light Bulbs not showing the correct status

### ISSUE THREAD

**Issue by amdjml** [NorthernMan54/homebridge-tasmota#34]
Hi,

I have 2 Tesmota light bulbs that are connected to Homebridge. I am able to turn the lights on but the status does not update in the Home app. It shows as off. When I click on them again, it does not turn the lights off.

![IMG_7006](https://user-images.githubusercontent.com/875782/132606646-2ff84be0-07dc-4d68-aa74-88049f30b6d6.jpg)

Here is what my tesmota light bulb mqtt settings look like:
<img width="332" alt="Screen Shot 2021-09-08 at 9 21 51 PM" src="https://user-images.githubusercontent.com/875782/132606657-e6c6b5a3-190e-49c6-9cca-9a35407474ff.png">

**Comment by NorthernMan54** [comment]
That is weird, have you tried resetting the setup/config by entering setoption19 0, then setoption19 1 in the device console?

**Comment by amdjml** [comment]
I just did that, do I need to restart HB or is that not important?

**Comment by NorthernMan54** [comment]
It should be automatic without restarting homebridge

**Comment by amdjml** [comment]
This is what I see in HB after doing SO19 0 & SO19 1

`[9/8/2021, 10:57:12 PM] [Tasmota] Updating 'feit_bulb_1' to {"Time":"2021-09-08T22:57:12","Uptime":"17T00:02:25","UptimeSec":1468945,"Heap":23,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"MqttCount":9,"POWER":"ON","Dimmer":3,"Color":"4,3,8,0,0","HSBColor":"255,68,3","White":0,"CT":366,"Channel":[2,1,3,0,0],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"xxxx","BSSId":"xxxx","Channel":1,"Mode":"11n","RSSI":70,"Signal":-65,"LinkCount":6,"Downtime":"0T00:00:11"}}`

The button in the Home app still shows as off

**Comment by NorthernMan54** [comment]
Can you share your tasmota device config and version?

**Comment by amdjml** [comment]
How do I do that?

**Comment by amdjml** [comment]
Here is the value for template I am using:
`{"NAME":" BPA800/RGBW/AG/2","GPIO":[0,0,0,0,2912,416,0,0,417,2976,2944,0,0,0],"FLAG":0,"BASE":18}`

Tasmota version: 9.5.0

**Comment by BNoiZe** [comment]
I have exactly the same problem with some devices. They show as off, even if they are on. When I try to switch them on Homekit instantly shows them as off again.

**Comment by BNoiZe** [comment]
> Here is the value for template I am using:
> `{"NAME":" BPA800/RGBW/AG/2","GPIO":[0,0,0,0,2912,416,0,0,417,2976,2944,0,0,0],"FLAG":0,"BASE":18}`
> 
> Tasmota version: 9.5.0

Could it be that you are using an Apple TV or HomePod with tvOS 15 on it? As the problem appeared following a recent update this could be the culprit.

**Comment by iChUdY** [comment]
I have this problem to. Everything on ios15, atv15, tasmota 9.5.0. Bulb turn on, but in home app delayed switch to off.

**Comment by BNoiZe** [comment]
As this problem started with iOS 15 beta and tvOS 15 beta I am certain that the problem is not this plugin. It might be that something change with HomeKit and now there’s a display error in the app.

**Comment by amdjml** [comment]
> > Here is the value for template I am using:
> > `{"NAME":" BPA800/RGBW/AG/2","GPIO":[0,0,0,0,2912,416,0,0,417,2976,2944,0,0,0],"FLAG":0,"BASE":18}`
> > Tasmota version: 9.5.0
> 
> Could it be that you are using an Apple TV or HomePod with tvOS 15 on it? As the problem appeared following a recent update this could be the culprit.

I do have iPhone and HomePod Mini on iOS 15.

**Comment by amdjml** [comment]
> As this problem started with iOS 15 beta and tvOS 15 beta I am certain that the problem is not this plugin. It might be that something change with HomeKit and now there’s a display error in the app.

Hopefully this plugin gets updated to work with the new iOS version.

**Comment by NorthernMan54** [comment]
I'm wondering if this is the cause, Tasmota 9.5.0 ?

![image](https://user-images.githubusercontent.com/19808920/136794566-63b75333-755b-4fe8-91cd-66f805a99013.png)
