### ISSUE TITLE
Gosund P1 devicetype change from switch to outlet

### ISSUE THREAD

**Issue by banjohb** [NorthernMan54/homebridge-tasmota#38]
My Gosund P1 flashed with Tasmota 8.5.1 shown as "switch" in HomeKit.

Is there a possibility to change the devicetype in "outlet"?

I tried override with "outlet" - nothing changed.

**Comment by NorthernMan54** [comment]
Outlet is not a supported option, and co-incidently not part of the interface I'm using

https://www.home-assistant.io/docs/mqtt/discovery/
