### ISSUE TITLE
Not tasmota device found in TasUI

### ISSUE THREAD

**Issue by reinisb** [NorthernMan54/homebridge-tasmota#39]
A clean install of homebridge, homebridge-tasmota, Mosquitto all running on my raspberry pi 3, but I cannot seem to be able to find my tasmota device in TasUI. I did the  setOption19 1 on console of my Sonoff Basic R3, but nothing helps. Can someone please help? Here are all the screenshots. Thank you!

<img width="813" alt="Screen Shot 2021-11-28 at 22 30 15" src="https://user-images.githubusercontent.com/6346595/143784790-c798d769-836b-4700-aee6-b6d9f776a931.png">
<img width="916" alt="Screen Shot 2021-11-28 at 22 28 37" src="https://user-images.githubusercontent.com/6346595/143784795-38cab6db-43db-4b47-ab85-f09ab3ea5709.png">
<img width="917" alt="Screen Shot 2021-11-28 at 22 28 25" src="https://user-images.githubusercontent.com/6346595/143784796-8db338be-6b79-44ff-a9e3-57a31cc859b3.png">
<img width="1111" alt="Screen Shot 2021-11-28 at 22 27 45" src="https://user-images.githubusercontent.com/6346595/143784797-fce7cfd1-c68a-4c30-b93a-cc9b32d41b1b.png">
<img width="1102" alt="Screen Shot 2021-11-28 at 22 27 26" src="https://user-images.githubusercontent.com/6346595/143784798-26c15da9-af59-4203-8682-d0c29a9664b0.png">
<img width="1107" alt="Screen Shot 2021-11-28 at 22 27 15" src="https://user-images.githubusercontent.com/6346595/143784800-c2781673-72fe-4137-b06c-c2e9b0725276.png">

**Comment by NorthernMan54** [comment]
A couple of comments

1 - Tasui is not dependent on mosquito, homebridge or this plugin and is totally independent of this.

2 - the GitHub repo for tasui is here https://github.com/IOTReboot/TasUI

3 - I always scan my whole subnet for devices, and not just the 1

4 - is it maybe the latest version of tasmota causing the issue?

**Comment by reinisb** [comment]
@NorthernMan54 Thanks for the quick response! I must mention that I am new to this, hence I'm not sure where the issue is. Can you please have a look at my config in the screenshots? I bet there is a mistake somewhere. Thanks!

**Comment by reinisb** [comment]
Actually nevermind, I now used https://www.npmjs.com/package/homebridge-mqttthing to set everything up successfully. Closing the issue.
