### ISSUE TITLE
Devices not being discovered

### ISSUE THREAD

**Issue by saabirsa** [NorthernMan54/homebridge-tasmota#4]
I have a number of devices connected to Homebridge and HA, however only some of these are being picked up by this plugin.
I have ensured `SetOption19` is set to `1` on all devices - this has been confirmed via both the console and toggling via HA

The topic for all devices is generally the device name - for example, `side_floodlight`, and the full topic is always `'%prefix%/%topic%/'`

The devices that are not appearing are as follows:

- 2x Sonoff Mini's
- 2x BME680's set as Generic
- 1x Arilux LC06 in CW/WW mode (unsupported, and a separate feature request for this has been raised)

My main Homebridge server is a Windows machine, however I have set up a separate instance on a Raspberry Pi in order to test this plugin. Please let me know if you require any specific information/logs in order to debug.

**Plugin Config:**
```
{
    "bridge": {
        "name": "Homebridge 1E23",
        "username": "xxxxx",
        "port": 51784,
        "pin": "874-93-933"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Tasmota",
            "mqttHost": "192.168.1.5:1883",
            "cleanup": 1,
            "debug": true,
            "platform": "Tasmota"
        }
    ]
}
```

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.1.3
* **Node.js Version**: v12.18.3
* **NPM Version**: v6.14.8
* **Operating System**: Raspbian

**Comment by saabirsa** [comment]
Strange - I did another `setoption19` and then` setoption19 1` on the Tasmota Console, and it seems the re-broadcasting of the HA entries have been picked up this time by the plugin.
Pleased to say that all the devices now work as expected, with the Arilux LC06 in CW/WW mode having a brightness slider also.

**Comment by NorthernMan54** [comment]
Awesome, this is great news tks
