### ISSUE TITLE
Historical graphs incorrect

### ISSUE THREAD

**Issue by Dero99** [NorthernMan54/homebridge-tasmota#40]
**Describe Your Problem:**

I have three ESP8266 Tasmota devices with AM2301 sensors.  The devices all have unique names and each devices Temp, Dew and Humidity information shows up correctly in the Home App and Eve App.  Historical data is enabled in Homebrigde-Tasmota.  I view the Historical data in Eve App and the only correct data is for Humidity, this is correct for all three ESP8266.  But the Dew and Temp data and graphs are straight line with 0.0 data points every 10 mins with odd bumps to +49 and -159 Celsius.  If I turn off a device, it shows as unreachable in Home but still has historical data 0.0 being added, with the odd random data points. 
**Logs:**

```
Show the Homebridge logs here with the DEBUG flag set, remove any sensitive information.
```

**Tasmota Device Config:**

```
Please include the Tasmota Module Type / Configuration and Template ( if used )
```

**Screenshots:**

**Environment:**

* **Tasmota Version**: sensors 10.0.0
* **Plugin Version**:0.0.124
* **Homebridge Version**:  1.3.4
* **Node.js Version**:  14.16.1
* **NPM Version**:  6.14.12
* **Operating System**:  macOS

![IMG_1441](https://user-images.githubusercontent.com/25590910/145634841-a1dc84b7-827d-4424-a5e0-bce8e59a1c3b.PNG)
![IMG_1442](https://user-images.githubusercontent.com/25590910/145634856-0d4ce725-1a2b-4dfc-99b2-17531a9d653e.PNG)
![IMG_1443](https://user-images.githubusercontent.com/25590910/145634858-68f8c2cd-a4bd-4a66-a3e8-42e05cc6ee70.PNG)
![IMG_1444](https://user-images.githubusercontent.com/25590910/145634860-d4ad98c5-c80e-4a1d-9d6c-b9defc73da8f.PNG)

**Comment by NorthernMan54** [comment]
Can you include your tasmota device config, I want to see if I can recreate the issue.

**Comment by Dero99** [comment]
Hi

This one from grow-room Sensor.  I feel it is odd that I get spikes in the graphs, but 0.0 most of the time. I assume the Homebridge aedes must be configured correctly and working because the three sensors humidity is logged correctly. 
I can get the other two configs tomorrow as it looks like my router rebooted and those IPs have changed…

Darrell

**Comment by NorthernMan54** [comment]
I was looking at your charts while waiting for the config, and one comment, the graphing library only supports a single graph of each type per accessory.  So I’m wondering if the dew point is confusing things.

**Comment by Dero99** [comment]
I saw that note on a different persons issue, but I hoped it was two physical sensors attached to a ESP, not a sensor with 2 internal sensors. I’ve no idea how to disable the Dew, don’t need it. 
Any temp sensors to try instead of DHT22 you’d know work?

Darrell

**Comment by NorthernMan54** [comment]
With filterDeny you can tell the plugin to ignore specific sensors, you just need to identify the discovery message for the one you want to remove from the log when running in debug mode.

1 - Enable the plugin debug option, and restart Homebridge

2 - Watch the log for a`Discovered` message from the dew temperature sensor

It will look like this in the log

```
 Tasmota:platform Discovered -> homeassistant/light/2E5F50_LI_1/config Powder Room {
  name: 'Powder Room',
  cmd_t: 'tasmota_2E5F50/cmnd/POWER',
  stat_t: 'tasmota_2E5F50/tele/STATE',
  val_tpl: '{{value_json.POWER}}',
  pl_off: 'OFF',
  pl_on: 'ON',
  avty_t: 'tasmota_2E5F50/tele/LWT',
  pl_avail: 'Online',
  pl_not_avail: 'Offline',
  uniq_id: '2E5F50_LI_1',
  dev: { ids: [ '2E5F50' ], connections: [ [Array] ] },
  '~': 'tasmota_2E5F50/',
  bri_cmd_t: 'tasmota_2E5F50/cmnd/Dimmer',
  bri_stat_t: 'tasmota_2E5F50/tele/STATE',
  bri_scl: 100,
  on_cmd_type: 'brightness',
  bri_val_tpl: '{{value_json.Dimmer}}',
  tasmotaType: 'light'
} +3ms
```

3 - Determine the unique id of the sensor, in my example it is `2E5F50_LI_1`

4 - Remove the accessory from Homebridge by going into the Tasmota console on the device and entering `setoption19 0`.   This will remove the device and its current config from Homebridge

5 - Add a filter deny entry for it in config.json

```
  "filterDeny": [ "2E5F50_LI_1" ]
```

6 - Restart Homebridge

7 - Add the device back to homebridge by going into the Tasmota console on the device and entering `setoption19 1`.  This time it should not create the Dew temperature sensor.

**Comment by Dero99** [comment]
Dews all disabled, so the 3 ESP8622 are each reporting one temp each. First reboot and Eve.app updated temp graphs correctly, but all afterwards were logged with 0.0 or worse. Reported temps and humidity are correct.


Darrell

**Comment by NorthernMan54** [comment]
Tasmota device config ?

**Comment by Dero99** [comment]
Sent you a dump a few days ago.  Here is some txts made with ATS oat decode-config app.



Darrell

**Comment by NorthernMan54** [comment]
If you update to the latest version this should be resolved for the graphs going forward.

**Comment by Dero99** [comment]
Excellent, works as advertised!

Thanks and my winter tomatoes thank you. 

Darrell
