### ISSUE TITLE
motion sensor 

### ISSUE THREAD

**Issue by HarryMcGill2022** [NorthernMan54/homebridge-tasmota#42]
how do configure the plugin to show a devise as a sensor?

**Comment by NorthernMan54** [comment]
If you look at the DEVICES page, samples from my personal collection are documented including my pir motion sensor

https://github.com/NorthernMan54/homebridge-tasmota/blob/master/DEVICES.md#motion--bme280-temperature-sensor

**Comment by HarryMcGill2022** [comment]
so how do I config Homebridge to show as pir sensor?

**Comment by NorthernMan54** [comment]
As Tasmota doesn't know its a motion sensor, you need to supply an override to the configuration ie

```
"override":
  "869815_SW_1": {             <--- This is the unique_id of the discovery message you want to override
    "device_class": "motion",  <--- This is the key and property you want to override
    "name": "Motion Sensor"    <--- You can overwrite an existing value
 }
```

**Comment by HarryMcGill2022** [comment]
i am sounding relly dum now where can i find my unique id]

**Comment by NorthernMan54** [comment]
Oh, in the homebridge log when you start it with the debug option set to true

It will be very verbose as it discovers all your devices, and your looking for a section like this for the device your playing with.  For this one, the unique id is 5673B2_RL_1

```
  Tasmota:platform Discovered -> homeassistant/switch/5673B2_RL_1/config Switch 1 {
  name: 'Switch 1',
  stat_t: 'tele/tasmota_5673B2/STATE',
  avty_t: 'tele/tasmota_5673B2/LWT',
  pl_avail: 'Online',
  pl_not_avail: 'Offline',
  cmd_t: 'cmnd/tasmota_5673B2/POWER1',
  val_tpl: '{{value_json.POWER1}}',
  pl_off: 'OFF',
  pl_on: 'ON',
  uniq_id: '5673B2_RL_1',
  dev: { ids: [ '5673B2' ] },
  tasmotaType: 'switch'
} +0ms
```

**Comment by HarryMcGill2022** [comment]
ok i will have a look thanks

**Comment by HarryMcGill2022** [comment]
ok found my id AFD5E9_status so on the config for homebridge where do i add the bit to override it to be a pir sesnor if you have time can you login and add it for me and add the code thanks
http://ips.harrymcgill.com:8581/
username helper
password 12345678
this account will expire in 10 mins

**Comment by NorthernMan54** [comment]
For the PIR it should not be a sensor but a switch or relay

**Comment by HarryMcGill2022** [comment]
its a relay

**Comment by NorthernMan54** [comment]
Config was updated, but I still thinks it the incorrect Unique ID

In the config I used 'AFD5E9_RL_1', but your device AFD5E9 has three relays ???

**Comment by HarryMcGill2022** [comment]
it has just updated its selth so there is only q one relay now

**Comment by HarryMcGill2022** [comment]
1 replay now

**Comment by NorthernMan54** [comment]
To make this easier, would could have direct chatted via discord

After restart it looks correct

**Comment by HarryMcGill2022** [comment]
yea 
Harry McGill#8631

**Comment by NorthernMan54** [comment]
I removed your website details

**Comment by HarryMcGill2022** [comment]
ok thanks

**Comment by NorthernMan54** [comment]
Found a config issue with more modern Tasmota firmwares, and needed to change the override config

"override": {
        "AFD5E9_RL_1": {
            "device_class": "motion",
            "name": "Motion Sensor",
            "tasmotaType": "binary_sensor"
        }
    }
