### ISSUE TITLE
RGB light support with Tasmota 10+ not working

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-tasmota#43]
**Describe The Bug:**

When using RGB lights or LED strips the ability to change colors is not available when using Tasmota 10+.  Until resolved, please use Tasmota versions less than 10.x.x.

**Comment by TimVerheul** [comment]
If I look into the code, this should be easy to implement. If im correct, the only file that needs to be updated is tasmotaLightService.ts right? Or is the rgb_cmd used anywhere else?

It seems that you already got support for changing colors to HSB. This is very useful

**Comment by NorthernMan54** [comment]
Only tasmotaLightService.ts handles color lights and led strips.

**Comment by TimVerheul** [comment]
After downgrading to 9.5, The bulb is fixed.
But this is still not showing up in HomeKit
![image](https://user-images.githubusercontent.com/29889196/151680316-3ac51633-0fe9-4b1d-a860-2a7af6183562.png)

**Comment by NorthernMan54** [comment]
Do a discovery to add a new accessory on the home app.  I used a tv accessory to enable a selector for the various effects available,

**Comment by TimVerheul** [comment]
Oh I see, I needed to go to the available items for homekit and there was the accessory. Thank you this was not clear for me

**Comment by TimVerheul** [comment]
The combination of changing the color in automations + setting a light effect doesn't work. for example: use the "Wakeup" effect but make the color purple is not working because if you change the color of the light it need to be turned on

**Comment by NorthernMan54** [comment]
Glad to see you got this working

**Comment by TimVerheul** [comment]
This issue is still present, because I downgraded to 9.5 and it doesn't properly work on Tasmota 9.5+

**Comment by phdoerfler** [comment]
Whilst "don't upgrade" might be an OK workaround for those who started with an old tasmota installation, my devices are all on Tasmota 11 and the Tasmota docs are very clear on that you should not downgrade.
I'd really like to see this resolved! I tried putting a bounty on this on bountysource.com but their sign-up process seems to have hiccupped on my e-mail.

**Comment by phdoerfler** [comment]
There we go: https://app.bountysource.com/issues/105666298-rgb-light-support-with-tasmota-10-not-working

**Comment by NorthernMan54** [comment]
Everyone, finally got a spare moment to put together a test device and update it to Tasmota 11.x.x.  The change was pretty straight forward and should make the colour's a little bit better.  Previously I was converting from RGB to HSB and back, but now it is just HSB within HomeKit and Tasmota.  So no minor colour issues due to data conversion.
