### ISSUE TITLE
Set Disconnected Device Cleanup Timing to infinite

### ISSUE THREAD

**Issue by Katoz96** [NorthernMan54/homebridge-tasmota#46]
I want to disable the auto cleanup feature, I've tried to set `Disconnected Device Cleanup Timing` to 0 and so far it's not giving me any problems but I would like to know if this is the correct solution.

Thanks for the help

**Comment by NorthernMan54** [comment]
Try changing the device cleanup time to a large number instead, under the covers it is using nodeJS setTimer, which has a maximum value of 596 hours aka 24 days.

**Comment by Katoz96** [comment]
Thanks, can you add this information below the option? I tried a larger number earlier, it deleted all my accessories and I didn't understand why

**Comment by NorthernMan54** [comment]
Good suggestion, will add during the next release

**Comment by NorthernMan54** [comment]
Fixed with https://github.com/NorthernMan54/homebridge-tasmota/releases/tag/0.2.1
