### ISSUE TITLE
Support for Node >=18

### ISSUE THREAD

**Issue by mkarras** [NorthernMan54/homebridge-tasmota#48]
**Is your feature request related to a problem? Please describe:**
More and more plugins require Node 18. (e.g. homebridge-ewelink >=18.18.2 or homebridge-config-ui-x >=18). Starting from today Homebridge requires Node 18.15.
Because homebridge-tasmota does not support Node 18 these plugins and Homebridge are stuck to older versions. The server stuck to Node 16.

**Describe the solution you'd like:**
Homebridge-tasmota support Node >=18.

**Describe alternatives you've considered:**
Is there a way to run homebridge-tasmota in a child bridge that runs an older Node version like Node 16.20.2 (currently using this version because of homebridge-tasmota)?

**Comment by NorthernMan54** [comment]
@mkarras I must be missing something, but where are you seeing it being stuck on Node 16 ?


My local production instance is on NodeJS 18

![image](https://github.com/NorthernMan54/homebridge-tasmota/assets/19808920/f79e9f61-996e-491b-9318-a3a2d826f99a)

**Comment by mkarras** [comment]
I was thinking that I had to downgrade to Node 16 because of homebridge-tasmota some time ago. Potentially it was because of an other plugin. Not sure anymore. 😅🙈

Thank you and keep doing awesome stuff. ❤️
